import torch

from pqdt.data.shapenet55 import BaseShapeNetPointDataset


class DeformedShapeNetDataset(BaseShapeNetPointDataset):
    """ShapeNet point clouds whose source inputs are generated by online deformation."""

    def __init__(self, cfg, split):
        dataset_cfg = cfg["dataset"] if isinstance(cfg, dict) else cfg.dataset
        if isinstance(dataset_cfg, dict):
            cars_only = bool(dataset_cfg.get("cars_only", False))
        else:
            cars_only = bool(getattr(dataset_cfg, "cars_only", False))
        super().__init__(cfg, split, cars_only=cars_only)


def gabor_kernel_batched(x, direction, freq=1.0, sigma=1.0, phase=0.0):
    x_proj = (x * direction.unsqueeze(1)).sum(dim=-1)
    gaussian = torch.exp(-0.5 * (x_proj / sigma) ** 2)
    sinusoid = torch.cos(2 * torch.pi * freq * x_proj + phase)
    return gaussian * sinusoid


def gabor_noise_3d_batched(x, num_kernels=16, freq=2.0, sigma=0.5, seed=42):
    if seed > 0:
        generator = torch.Generator(device=x.device)
        generator.manual_seed(seed)
    else:
        generator = None

    batch_size, num_points, _ = x.shape
    device = x.device
    noise = torch.zeros_like(x)

    for axis in range(3):
        total = torch.zeros(batch_size, num_points, device=device)
        for _ in range(num_kernels):
            direction = torch.randn(batch_size, 3, device=device, generator=generator)
            direction = direction / direction.norm(dim=-1, keepdim=True)
            offset = torch.rand(batch_size, 1, 3, device=device, generator=generator) * 10 - 5
            phase = torch.rand(batch_size, 1, device=device, generator=generator) * 2 * torch.pi
            total += gabor_kernel_batched(x - offset, direction, freq, sigma, phase)
        noise[:, :, axis] = total / num_kernels

    return noise


def deform_point_cloud_with_gabor_batched(points, scale=0.05, **kwargs):
    noise = gabor_noise_3d_batched(points, **kwargs)
    return points + scale * noise
